# Numpy:


- Numpy is a Python library created in 2005 that performs **numerical calculations.** It is generally used for working with **arrays.**


- The Numpy library contains multidimensional array data structures. 



- Numpy arrays are optimized for complex **mathematical and statistical operations.** Operations on NumPy are up to 50x faster than iterating over native Python lists using loops.


**Import NumPy in Python**

In [1]:
import numpy as np

**Numpy Array Creation**

- An array allows us to store a collection of multiple values in a single data structure.


- The Numpy array is similar to a list, but with added benefits such as being faster and more memory efficient.


- NumPy is usually imported under the np alias. **alias:** In Python alias are an alternate name for referring to the same thing.


- Create an alias with the as keyword while importing

In [2]:
import numpy as np

a=np.array([2,4,6,8,10])
print(a)

[ 2  4  6  8 10]


In [3]:
# We can create a NumPy array using a Python List

a = [2,4,6,8,10]

b= np.array(a)             # create numpy array using list1

print(b)


[ 2  4  6  8 10]


The **np.zeros()** function allows us to create an array filled with all zeros. For example,

In [4]:
a=np.zeros(4)
print(a)

[0. 0. 0. 0.]


NumPy is used to work with arrays. The array object in NumPy is called ndarray.

In [5]:
import numpy as np
a = np.array([2,4,6,8])
print(a)
print(type(a))


[2 4 6 8]
<class 'numpy.ndarray'>


Use a **tuple** to create a NumPy array:

In [6]:
a=np.array((2,4,6,8))
print(a)

[2 4 6 8]


**Random Array**
- The random module's **rand()** method returns a random float between 0 and 1.

- The **randint()** method takes a **size** parameter where you can specify the shape of an array.

In [7]:
from numpy import random
x = random.rand()

print(x)

0.3235357251216887


In [8]:
# Generate a 1-D array containing 6 random integers from 0 to 50.

np.random.randint(0,50,size=(6))

array([25,  9, 45, 12,  2, 29])

In [9]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 50.

np.random.randint(0,50, size=(3, 5))


array([[42, 24,  1,  6,  1],
       [16,  8, 48, 42, 21],
       [25, 28, 25,  3, 18]])

## Dimensions in Arrays:

- A dimension in arrays is one level of array depth (nested arrays).

- nested array: are arrays that have arrays as their elements.

In [10]:
# Create a 0-D array with value 50
s=np.array(50)
print(s)

50


In [11]:
# Create a 1-D array containing the values 1,2,3,4,5.

b=np.array([1,2,3,4,5])
print(b)

[1 2 3 4 5]


In [12]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6

c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [13]:
# Create a 3-D array 
d= np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
print(d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


NumPy Arrays provides the **ndim** attribute that returns an integer that tells us **how many dimensions** the array have.

In [14]:
print(s.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns.

array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8], 
                [9, 10, 11, 12]],
                     
                [[13, 14, 15, 16], 
                 [17, 18, 19, 20], 
                 [21, 22, 23, 24]]])
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### Access Array Elements:

In [16]:
# Get the first  element from the following array.

a=np.array([1,2,3,4,5])
print(a[0])


1


In [17]:
# Get 1st and 2nd  elements from the following array add them.

a=np.array([1,2,3,4,5])
print(a[0] + a[1])

3


In [18]:
# change the value of the first element

a[0] = 12
print(a)

[12  2  3  4  5]


In [19]:
# access the last element use negative indexing
print(a[-1])  

5


### Numpy Array Slicing:

- Array Slicing is the process of extracting a portion of an array.


- With slicing, we can easily access elements in the array. It can be done on one or more dimensions of a NumPy array.

- **Syntax** array[start : stop: step]


In [20]:
import numpy as np
a = np.array([1, 3, 5, 7, 8, 9, 2, 4, 6])
print(a)

[1 3 5 7 8 9 2 4 6]


In [21]:
# slice a from index 2 to index 6 (exclusive)
print(a[2:6])  # [5 7 8 9]

[5 7 8 9]


 slice a from index 0 to index 8 (exclusive) with a step size of 2

In [22]:
print(a[0:8:2])  # [1 5 8 2]

[1 5 8 2]


In [23]:
# slice a from index 3 up to the last element
print(a[3:])  # [7 8 9 2 4 6]

[7 8 9 2 4 6]


**Syntax of 2D Numpy Array Slicing**

- row_start, row_stop, row_step ----> specifies starting index, stopping index, and step size for the rows respectively


- col_start,col_stop,col_step -------> specifies starting index, stopping index, and step size for the columns respectively

In [24]:
# slice the a to get the first two rows and columns
a = np.array([[1, 3, 5, 7],[9, 11, 13, 15]])

print(a[0:2, 0:2])

[[ 1  3]
 [ 9 11]]


In [25]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


## Data Types:

A data type is a way to specify the type of data that will be stored in an array.

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j





The Numpy array object has a property called **dtype** that returns the data type of the array



In [26]:
import numpy as np
a = np.array([2, 4, 6])  #integers 

# check the data type of a
print(a.dtype)

int32


In [27]:
b=np.array([1+2j, 2+3j, 3+4j])  #complex numbers
c = np.array([0.1, 0.2, 0.3])    #floating-point numbers
print(b.dtype)
print(c.dtype)

complex128
float64


In Numpy, we can **convert the data type** of an array using the **astype()** method. For example,

In [28]:
import numpy as np

int = np.array([1, 3, 5, 7]) #  of integers

# convert data type of int_array to float
float = int.astype('float')

# print the arrays and their data types
print(int, int.dtype)
print(float, float.dtype)

[1 3 5 7] int32
[1. 3. 5. 7.] float64


## Numpy Array Copy vs View:


The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [29]:
# Make a view, change the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 50

print(arr)
print(x)

[50  2  3  4  5]
[50  2  3  4  5]


In [30]:
# Make a copy, change the original array.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


## Numpy Array Shape and Reshape:


- The **shape** of an array is the number of elements in each dimension.


- Numpy array **reshaping** simply means changing the shape of an array without changing its data.


- **reshaping** is used to Array Manipulation Functions



- We can reshape this 1D array into N-d array as

In [31]:
# print the shape of a 2-D array:
import numpy as np
a=np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)
print(a.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [32]:
#Syntax  Reshaping

#      np.reshape(array, newshape, order = 'C')

In [33]:
import numpy as np

b = np.array([1, 3, 5, 7, 2, 4, 6, 8])

# reshape a 1D array into a 2D array 
# with 2 rows and 4 columns
result = np.reshape(b, (2, 4))
print(result)

[[1 3 5 7]
 [2 4 6 8]]


In [34]:
# From 1-D to 3-D

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new= arr.reshape(2, 3, 2)
print(arr)

print(new)
print(new.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


In [35]:
# Convert the array  From 2-D to 1D array:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)
print(newarr)


[1 2 3 4 5 6]


## Iterating:

**Iterating** means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

In [36]:
# Iterate on the elements of the following 1-D array
import numpy as np

a= np.array([1, 2, 3])
for x in a:
    print(x)


1
2
3


In [37]:
# Iterate on the elements of the following 2-D array

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


## Joining NumPy Arrays:

- Joining means putting contents of two or more arrays in a single array.
- we want to join to the **concatenate()** function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [38]:
#Join two arrays

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [39]:
# Join two 2-D arrays along rows

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


## Searching Arrays:

- we can search an array for a certain value, and return the indexes that get a match.

- To search an array, use the where() method.

In [40]:
# Find the indexes where the value is 6
import numpy as np

arr = np.array([1, 2, 3, 6, 5, 6, 6])

z = np.where(arr == 6)
print(z)

# Which means that the value 4 is present at index 3, 5, and 6

(array([3, 5, 6], dtype=int64),)


In [41]:
import numpy as np

k = np.array([1, -2, -3, 4, 5])

result = np.where(k<0 )
print(result)


(array([1, 2], dtype=int64),)


**Sorting Arrays**

Sorting means putting elements in an ordered sequence.

In [42]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


If we use the sort() method on a 2-D array, both arrays will be sorted:

In [43]:
import numpy as np
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In Numpy, attributes are properties of Numpy arrays that provide information about the array's shape, size, data type,  
dimension, and so on.

In [44]:
import numpy as np


array = np.array([[2, 4, 6],[1, 3, 5]])

print(array.ndim)
print(array.size)
print(array.shape)
print(array.dtype) 


2
6
(2, 3)
int32


## Numpy Arithmetic  Operations:


Numpy provides a wide range of operations that can perform on arrays, including arithmetic operations.


Here's a list of various arithmetic operations.

- Addition	
- Subtraction	
- Multiplication	
- Division	
- Exponentiation	
- Modulus

we can use the both + operator and the built-in function add() to perform element-wise addition between two Numpy arrays.

In [45]:
import numpy as np

first_array = np.array([1, 3, 5, 7])
second_array = np.array([2, 4, 6, 8])

# using the + operator
result1 = first_array + second_array
print(result1) 

# using the add() function
result2 = np.add(first_array, second_array)
print(result2) 

[ 3  7 11 15]
[ 3  7 11 15]


For element-wise multiplication, we can use the * operator or the multiply() function.

In [46]:
# similary we can use  Subtraction, Division, Exponentiation, Modulus

# multiplication-------->   ( * )    or    multiply() function
# Subtraction------------>  ( - )    or    subtract() function.
# Division--------------->  ( / )    or    divide()   function.
# Exponentiatiom--------->  ( ** )   or    power()    function.
#  Modulus--------------->  ( % )    or    mod()     function.

**Comparison Operators**

Numpy provides various element-wise comparison operators that can compare the elements of two Numpy arrays.

In [47]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([3, 2, 1])

result1 = array1 < array2
result11 = np.less(array1, array2)
print(result1)              # less than operator
print(result11)


result2 = array1 > array2
print(result2)    # greater than operator

result3 = array1 == array2
print(result3)    # equal to operator

[ True False False]
[ True False False]
[False False  True]
[False  True False]


In [48]:
# Numpy also provides built-in functions to perform all the comparison operations.

# less()
# less_equal()
# greater()
# greater_equal()
# equal()
# not_equal()

**Logical Operations**

As mentioned earlier, logical operators perform Boolean algebra; a branch of algebra that deals with True and False statements.

In [49]:
import numpy as np

x1 = np.array([True, False, True])
x2 = np.array([False, False, True])

# Logical AND
print(np.logical_and(x1, x2)) 


# Logical OR
print(np.logical_or(x1, x2)) 

# Logical NOT
print(np.logical_not(x1)) 

[False False  True]
[ True False  True]
[False  True False]


**Rounding Functions**

We use rounding functions to round the values in an array to a specified number of decimal places.

- **round()** :---	returns the value rounded to the desired precision
- **floor()** :---	returns the values of array down to the nearest integer that is less than each element
- **ceil()** :---	returns the values of array up to the nearest integer that is greater than each element.

In [50]:
# round the array to two decimal places
import numpy as np
num = np.array([1.23456, 2.34567, 3.45678, 4.56789])

round= np.round(num,2)
print(round)

[1.23 2.35 3.46 4.57]


In [51]:
# Rounds the values  down to the nearest integer that is less than or equal to each element
import numpy as np
num = np.array([1.23456, 2.34567, 3.45678, 4.56789])
floor = np.floor(num)
print(floor)

[1. 2. 3. 4.]


In [52]:
# rounds the values  up to the nearest integer that is greater than or equal to each element.
import numpy as np
num = np.array([1.23456, 2.34567, 3.45678, 4.56789])
ceil = np.ceil(num)
print(ceil)

[2. 3. 4. 5.]


## Numpy Statistical Functions:


- Statistics involves **gathering data, analyzing it, and drawing conclusions** based on the information collected.

Numpy provides us with various statistical functions that can perform statistical data analysis.

In [53]:
# The mean value of a Numpy array.

import numpy as np
marks= np.array([85,90,92,87,91])
mean= np.mean(marks)
print(mean)

89.0


In [54]:
# Mean of Numpy N-d Array

import numpy as np

array1 = np.array([[1, 3], [5, 7]]) # create a 2D array
print(array1)

# calculate the mean of the entire array
result1 = np.mean(array1)
print(result1)  

# calculate the mean along vertical axis (axis=0)
result2 = np.mean(array1, axis=0)
print(result2)  

# calculate the mean along  (axis=1)
result3 = np.mean(array1, axis=1)
print(result3) 

[[1 3]
 [5 7]]
4.0
[3. 5.]
[2. 6.]


In [55]:
# Here are some of the statistical functions provided by Numpy:


# np.median()----->return the median of an array

# np.std()--------->  return the standard deviation of an array
# np.percentile()-->return the nth percentile of elements in an array
# np.min()--------->return the minimum element of an array
# np.max()--------->return the maximum element of an array

In Numpy, we use the percentile() function to compute the nth percentile of a given array.

Here we can find 25%  and 75%of the values in array1 

In [56]:
import numpy as np

array1 = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19])

# compute the 25th percentile of the array
result1 = np.percentile(array1, 25)
print(result1)

# compute the 75th percentile of the array
result2 = np.percentile(array1, 75)
print(result2)

5.5
14.5


**Numpy String add() Function**

In Numpy, we use the np.char.add() function to perform element-wise string concatenation for two arrays of strings. For example,

In [57]:
import numpy as np

array1 = np.array(['iPhone: ', 'price: '])
array2 = np.array(['15', '$900'])

# perform element-wise array string concatenation
result = np.char.add(array1, array2)

print(result)

['iPhone: 15' 'price: $900']


In [58]:
import numpy as np  

array1 = np.array(['sachin', 'samskruthi', 'tejas'])
# capitalize the first letter of each string in array1 
result = np.char.capitalize(array1) 
# convert all string elements to uppercase
result1 = np.char.upper(array1)
# convert all string elements to lowercase
result2 = np.char.lower(array1)

print(result)
print(result1)
print(result2)


['Sachin' 'Samskruthi' 'Tejas']
['SACHIN' 'SAMSKRUTHI' 'TEJAS']
['sachin' 'samskruthi' 'tejas']


### Boolean Indexing:


In Numpy, boolean indexing allows us to filter elements from an array based on a specific condition.


In [59]:
array1 = np.array([12, 24, 16, 21, 32, 29, 7, 15])
boolean_mask = array1 > 20
print(boolean_mask)

[False  True False  True  True  True False False]


In [60]:
import numpy as np

# create an array of numbers
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# create a boolean mask
boolean_mask = array1 % 2 != 0

# boolean indexing to filter the odd numbers
result = array1[boolean_mask]
print(result)

[1 3 5 7 9]
